/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.panda.cloud.service.demo.ConsumerServiceApplication;
import org.junit.Test;

public class ConsumerServiceApplicationTest {
  @Test
  public void testAppHasAGreeting() {
    ConsumerServiceApplication classUnderTest = new ConsumerServiceApplication();
  }
}
