/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.panda.cloud.zuul.ZuulServerApplication;
import org.junit.Test;

public class ZuulServerApplicationTest {
  @Test
  public void testAppHasAGreeting() {
    ZuulServerApplication classUnderTest = new ZuulServerApplication();
  }
}
