/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.panda.cloud.service.demo.GreetingServiceApplication;
import org.junit.Test;

public class GreetingServiceApplicationTest {
  @Test
  public void testAppHasAGreeting() {
    GreetingServiceApplication classUnderTest = new GreetingServiceApplication();
  }
}
