/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.panda.cloud.eureka.EurekaServerApplication;
import org.junit.Test;

public class EurekaServerApplicationTest {
  @Test
  public void testAppHasAGreeting() {
    EurekaServerApplication classUnderTest = new EurekaServerApplication();
  }
}
